[HRM5]
type = 'ESpec_'
data_folder = '/chromox_cameras/HRM5/' 
data_stem = 'OD' # empty for some DAQs 
data_type = 'csv'
data_ext = '.csv'
calib_subfolder = './ESpecs/' # optional
calib_file = 'HRM5_calibs.toml'#'HRM5_transform_LAMP_1749111754935000.pkl'

[HRM6]
type = 'ESpec_'
data_folder = '/chromox_cameras/HRM6/' 
data_stem = 'OD' # empty for some DAQs 
data_type = 'csv'
data_ext = '.csv'
calib_subfolder = './ESpecs/' # optional
calib_file = 'HRM6_calibs.toml'#'HRM6_transform_LAMP_1749111754935000.pkl'

[HRM3]
type = 'ProfileCam_'
data_folder = '/chromox_cameras/HRM3/' 
data_stem = 'OD' # empty for some DAQs 
data_type = 'csv'
data_ext = '.csv'
calib_subfolder = './ProfileCam/'
calib_file = 'HRM3_calib.toml'

[HRM4]
type = 'ProfileCam_'
data_folder = '/chromox_cameras/HRM4/' 
data_stem = 'OD' # empty for some DAQs 
data_type = 'csv'
data_ext = '.csv'
calib_subfolder = './ProfileCam/'
calib_file = 'HRM4_calib.toml'  # contains nonsense for now