[HRM5]
type = 'ESpec_'
data_folder = '/chromox_cameras/HRM5/' 
data_stem = 'OD' # empty for some DAQs 
data_type = 'csv'
data_ext = '.csv'
calib_subfolder = './ESpecs/' # optional
calib_file = 'HRM5_calibs.toml'#'HRM5_transform_LAMP_1749111754935000.pkl'

[HRM6]
type = 'ESpec_'
data_folder = '/chromox_cameras/HRM6/' 
data_stem = 'OD' # empty for some DAQs 
data_type = 'csv'
data_ext = '.csv'
calib_subfolder = './ESpecs/' # optional
calib_file = 'HRM6_calibs.toml'#'HRM6_transform_LAMP_1749111754935000.pkl'

[SCOPE1]
type = 'BDot'
data_folder = '/scope_pool05720010/'
data_stem = 'scope1'
data_type = 'scope'
data_ext = '.csv'
calib_subfolder = './BDot/' # optional
calib_file = 'SCOPE1_calibs.toml'

[SCOPE2]
type = 'BDot'
data_folder = '/scope_pool05710001/'
data_stem = 'scope2'
data_type = 'scope'
data_ext = '.csv'
calib_subfolder = './BDot/' # optional
calib_file = 'SCOPE2_calibs.toml'

