# DAQ Required as a minimum. 
[setup]
DAQ = 'Fireball_DAQ_Bdot'

# Required. Well, data folder at least. Data is absolute path, Others relative to Root folder.
[paths]
calibs_folder = './calibs/'
user_diagnostics = 'diagnostics.' # this is as per python moadule loading. So '.' to represent folders
user_DAQs = 'DAQs.'
#diags_folder = /Users/los/Documents/GitHub/ZEUSJan2024/configs/
#calibs_folder = /Users/los/Documents/GitHub/ZEUSJan2024/calibs/