[1749111996135000]
notes = ''
start = {'shot' = 1749111996135000} # when timeframe starts
end = {'shot' = 1749153428535000} # when timeframe ends

[1749111996135000.roi]
stage = "original"
pixels = [
    [180, 0],
    [450, 375]
]
